import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from 'react-hot-toast'

import RegisterSW from "./RegisterSW";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const metadata = {
//   title: "My Portfolio",
//   description: "Portfolio built with Next.js PWA",
//   manifest: "/manifest.json",
//   themeColor: "#000000",
// };



// export const metadata = {
//   title: "My Portfolio",
//   description: "Portfolio built with Next.js as PWA",
//   manifest: "/manifest.json",
//   themeColor: "#000000",
// }

// export const metadata = {
//   title: "My Portfolio",
//   description: "Portfolio PWA with Next.js",
//   manifest: "/manifest.json",
//   icons: {
//     icon: "/icon-192x192.png",
//     shortcut: "/icon-192x192.png",
//     apple: "/icon-512x512.png",
//   },
//   themeColor: "#000000", // for PWA
// };



export const metadata = {
  title: "My Next.js PWA",
  description: "Next.js Progressive Web App",
  manifest: "/manifest.json",
  themeColor: "#000000",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head> <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" /> </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RegisterSW />
        <Navbar />
        {children}
        <Toaster position="top-center" reverseOrder={false} />
        <Footer />
      </body>
    </html>
  );
}
